language: go

go:
  - 1.14.6
  - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GO111MODULE=on
  - go build

script:
  - . ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
